name: Build DeadFace

on:
  push:
    branches: [ "main" ]
    tags:
      - v*
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r Dead_Marks/requirements.txt
          pip install pyinstaller

      - name: Build DeadFace (Linux)
        run: |
          pyinstaller DeadFace.spec

      - name: Zip files
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          filename: DeadFace_linux.zip
          path: dist/DeadFace

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_artifact_linux
          path: DeadFace_linux.zip

  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r Dead_Marks/requirements.txt
          pip install pyinstaller

      - name: Build DeadFace (Windows)
        run: |
          pyinstaller DeadFace.spec

      - name: Zip files
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          filename: DeadFace_windows.zip
          path: dist/DeadFace

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_artifact_windows
          path: DeadFace_windows.zip

  build_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r Dead_Marks/requirements.txt
          pip install pyinstaller

      - name: Build DeadFace (macOS)
        run: |
          pyinstaller DeadFace.spec

      - name: Zip files
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          filename: DeadFace_macos.zip
          path: dist/DeadFace

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_artifact_macos
          path: DeadFace_macos.zip

  release:
    name: Release pushed tag
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    needs: [ build_linux, build_macos, build_windows ]
    permissions:
      contents: write

    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
            --generate-notes

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: build_artifact_windows

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: build_artifact_linux

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: build_artifact_macos

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            DeadFace_windows.zip
            DeadFace_linux.zip
            DeadFace_macos.zip
